[project]
name = "octopus-data-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.4",
    "python-dotenv>=1.0.1",
    "pytz>=2024.2",
    "sqlalchemy>=2.0.36",
]
